### ISSUE TITLE
NetworkFirst caching strategy not working

### ISSUE THREAD

**Issue by josebailo** [vite-pwa/vite-plugin-pwa#537] opened 2023-06-13 12:43 UTC
Hi!

I'm using this plugin for first time and it looks to be working fine but for the `handler` on the `runtimeCaching` configuration. Here is my `vite.config.ts` file:

```ts
import { defineConfig, loadEnv } from 'vite'
import react from '@vitejs/plugin-react'
import tsconfigPaths from 'vite-tsconfig-paths'
import { VitePWA } from 'vite-plugin-pwa'

// https://vitejs.dev/config/
export default ({ mode }) => {
  process.env = {...process.env, ...loadEnv(mode, process.cwd())}
  return defineConfig({
    plugins: [
      react(),
      tsconfigPaths(),
      VitePWA({
        registerType: 'autoUpdate',
        workbox: {
          runtimeCaching: [
            {
              urlPattern: /\.js$/,
              handler: 'NetworkFirst',
              options: { cacheName: 'js-cache' },
            },
            {
              urlPattern: /\.css$/,
              handler: 'NetworkFirst',
              options: { cacheName: 'css-cache' },
            },
            {
              urlPattern: /\.ttf$/,
              handler: 'NetworkFirst',
              options: { cacheName: 'font-cache' },
            },
            {
              urlPattern: /\.html$/,
              handler: 'NetworkFirst',
              options: { cacheName: 'html-cache' },
            },
            {
              urlPattern: /\.ico$/,
              handler: 'NetworkFirst',
              options: { cacheName: 'icon-cache' },
            },
            {
              urlPattern: /\.(?:png|gif|jpg|jpeg|svg)$/,
              handler: 'NetworkFirst',
              options: { cacheName: 'images-cache' },
            },
          ]
        },
        manifest: {
          name: process.env.VITE_PWA_NAME,
          short_name: process.env.VITE_PWA_SHORT_NAME,
          description: process.env.VITE_PWA_DESCRIPTION,
          theme_color: process.env.VITE_PWA_THEME_COLOR,
          icons: [
            { src: '/icons/icon-72x72.png', sizes: '72x72', type: 'image/png' },
            { src: '/icons/icon-96x96.png', sizes: '96x96', type: 'image/png' },
            { src: '/icons/icon-128x128.png', sizes: '128x128', type: 'image/png' },
            { src: '/icons/icon-144x144.png', sizes: '144x144', type: 'image/png' },
            { src: '/icons/icon-152x152.png', sizes: '152x152', type: 'image/png' },
            { src: '/icons/icon-192x192.png', sizes: '192x192', type: 'image/png' },
            { src: '/icons/icon-384x384.png', sizes: '384x384', type: 'image/png' },
            { src: '/icons/icon-512x512.png', sizes: '512x512', type: 'image/png' },
          ],
        },
      }),
    ],
  })
}
```

It doesn't matter what I put on the `handler` it always works the same, the resources are served from cache. If I change something on the code the page must be reloaded twice. The first time uses the cached code and download the new version, and in the second one it uses the new version of the code. It looks like it's working like the stale while revalidate strategy... I want to use the network first approach so the cache is only used when the user is using the application offline, if not it should load and use the latest version from the server.

Any idea what can be wrong?

**Comment by userquin** [comment] 2023-06-13 13:31
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by userquin** 2023-06-13 13:31 UTC
