### ISSUE TITLE
Incorrect manifest generation

### ISSUE THREAD

**Issue by honungsburk** [vite-pwa/vite-plugin-pwa#520] opened 2023-05-20 13:49 UTC
Given certain conditions the manifest file isn't correctly generated. The name of the file changes and the generated result is missing several fields. As a user, I just expect the file to have a consistent name and that everything I'm specifying is copied to the generated file.

these options:
```ts
      VitePWA({
        registerType: "autoUpdate",
        devOptions: {
          enabled: false
        },
        includeAssets: [
          "robots.txt",
        ],
        manifest: {
          name: "ThisThing",
          short_name: "ThisThing",
          description: "To keep track of things",
          theme_color: "#ffffff",
          background_color: "#ffffff",
          icons: [
          ],
        },
      }),
```

generates the manifest file `manifest.webmanifest` when using the command `tsc && vite build`:

```ts
{"name":"ThisThing","short_name":"ThisThing","start_url":"/","display":"standalone","background_color":"#ffffff","lang":"en","scope":"/","description":"To keep track of things","theme_color":"#ffffff","icons":[]}

```

But if we add icons...

```ts
      VitePWA({
        registerType: "autoUpdate",
        devOptions: {
          enabled: false
        },
        includeAssets: [
          "robots.txt",
        ],
        manifest: {
          name: "ThisThing",
          short_name: "ThisThing",
          description: "To keep track of things",
          theme_color: "#ffffff",
          background_color: "#ffffff",
          icons: [
            {
              src: "/android-chrome-192x192.png",
              sizes: "192x192",
              type: "image/png",
            },
            {
              src: "/android-chrome-512x512.png",
              sizes: "512x512",
              type: "image/png",
            },
          ],
        },
      }),
```

it generates the file `site.webmanifest`:

```ts
{
    "name": "",
    "short_name": "",
    "icons": [
        {
            "src": "/android-chrome-192x192.png",
            "sizes": "192x192",
            "type": "image/png"
        },
        {
            "src": "/android-chrome-512x512.png",
            "sizes": "512x512",
            "type": "image/png"
        }
    ],
    "theme_color": "#ffffff",
    "background_color": "#ffffff",
    "display": "standalone"
}
```

**Comment by userquin** [comment] 2023-05-20 14:10
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by userquin** 2023-05-20 14:10 UTC
